### ISSUE TITLE
Plugin not working as expected on Chrome

### ISSUE THREAD

**Issue by mauriciogamboa** [nosilleg/capslockstate-jquery-plugin#2]
The plugin does not seem to work correctly on Chrome Version 33.0.1750.149. 

Steps to reproduce :
1. I started to type and it detects the caps lock is off.
2. I turned on caps and it detects the change just fine.
3. I turned in off but it does not detect the change, it says it's still on.

It works just fine in Fire Fox.

**Comment by nosilleg** [comment]
@mauriciogamboa Apologies.  I never received a notification about this.  Is this still an issue for you?  Does it happen on http://jsfiddle.net/nosilleg/zVCU5/  Are you using a virtual machine or is this happening on a base OS?
